name: Generate ascii artifact
on:
    push: 
jobs:
    build-job1:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Excecute cowsay CMD
              run: cowsay -f dragon "I am a dragon" >> dragon.txt
            
            - name: Upload dragon file
              uses: actions/upload-artifact@v4  
              with: 
                name: dragon text file
                path: dragon.txt
                # Name of the artifact to upload.
                # Optional. Default is 'artifact'
            
    test-job2:
        needs: build-job1
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon text file

            - name: Text file exists
              run: grep -i "dragon" dragon.txt

    deploy-job3:
        needs: test-job2
        concurrency: 
            group: production-deployment
            cancel-in-progress: true 
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon text file

            - name: Raead file
              run: cat dragon.txt
            
            - name: Deploy docker
              run: echo "Deploying....."
