name: Exploring Variables and secrets
on:
    push
jobs:
    docker-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Run docker
              run: $ docker run hello-world