name: Exploring Variables and secrets
on:
    push
jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: docker buildx build -t docker.io/dockerUsername/imageName:latest

            - name: Docker login
              run: docker login --username=dockerUsername--password:s3UrePaSsw0rd

            - name: Docker publish
              run: docker publish docker.io/dockerUsername/imageName:latest
    
    docker-deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
            - name: Run Docker
              run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

          